### ISSUE TITLE
Diet Restrictions are reversed. 

### ISSUE THREAD

**Issue by SpaceMeatball79** [Deadbones2000/Medieval-Origins#12]
Origins that are supposed to be herbivores can only eat meat and vice-versa.

**Comment by silversilenc3** [comment]
i've been having the same problem! specifically elf origin.

**Comment by BjornTjockPals** [comment]
I looks fixed, except elves. I checked some origins (avian, bee, wolf, werewolf, demon, elf) and it looks like diet restrictions are as intended (except elves).

Tested on 1.19
medieval origins 4.1.1

**Comment by BjornTjockPals** [comment]
Fixed in new update; can be closed.
