### ISSUE TITLE
the Orgins is not compatible with mod items

### ISSUE THREAD

**Issue by xXPLFOXPLXx** [Deadbones2000/Medieval-Origins#14]
when the paladin uses axe from vanilia minecraft , he hit extra dmg. but when he hitting with modded axes .
deals the same damage as the others orgins, Is it possible to fix it somehow change configs or add new mod.

**Comment by Deadbones2000** [comment]
I don't guarantee any mod compatibility. The mod is balanced around the vanilla game.
