### ISSUE TITLE
bug when switching origins with orb of origins or commands

### ISSUE THREAD

**Issue by zerevoidd** [Deadbones2000/Medieval-Origins#2]
if you switch to another origin, you still retain some of the properties of the previous one.

for example, chosing the original origin of a pixie and then switching to say, a necromancer, will cause you to levitate AND use the skeleton ability at the same time.

**Comment by Icebane583** [comment]
I've encountered this as well, picked Fae by mistake, wasn't paying attention. Spawned an orb of origin in to switch to Shulk. Now I have levitate and the Shulk inventory. I tried switching thru the console as well unfortunately that didn't work either. 

Is there a solution to this? None of us are using Fae so is there a way just to disable levitate?

**Comment by Deadbones2000** [comment]
This has been fixed in v4.1.1. I am not continuing support for 1.18 so if your character still has a residual power you or an admin should run /power revoke [playername] medievalorigins:[originname]/[powername]
