### ISSUE TITLE
[1.19.x-4.1.2] Dwarfs' Photoallergic Trait Does Not Detect All Helmets

### ISSUE THREAD

**Issue by Bereim** [Deadbones2000/Medieval-Origins#20]
As a Dwarf, I burned in sunlight despite wearing a Copper Helmet from Mythic Metals.

**Comment by Bereim** [comment]
Checked your code and saw that you checked against a list of vanilla helmets.

For better compatibility, I'd suggest you use the following and then blacklist any items you don't want to count.
```
{
  "type": "origins:equipped_item",
  "equipment_slot": "head",
  "item_condition": {
    "type": "origins:empty"
  }
}
```

**Comment by Deadbones2000** [comment]
No mod compatibility is provided for the mod. If you want it you can expand the list of helmets to include those from the mods you are using.
