### ISSUE TITLE
Can't respawn as Elf

### ISSUE THREAD

**Issue by xErrorAmelie** [Deadbones2000/Medieval-Origins#3]
When you select Elf as your origin it won't let you respawn. Also on first spawn you have to press ESC to see something. 
When you try to spawn it throws the following error in both cases.

Server log:
https://paste.corebot.dev/imiguyawur.rb

Mod Version: 4.0.3

**Comment by Deadbones2000** [comment]
This isn't related to my mod. Your origin is mythical_origins:elf which is from the Mythical Origins mod, not Medieval Origins. I'd advise you report it there for support on your issue.
